### ISSUE TITLE
vscode version 1.24 released

### ISSUE THREAD

**Issue by alculete** [snapcrafters/vscode#2]
As stated on the website https://code.visualstudio.com/updates/v1_24

**Comment by jrkoch** [comment]
I'm admittedly unfamiliar with writing snaps, but the links in snapcraft.yaml now point to 1.24.0 builds of vscode:

```yaml
parts:
  vscode:
    plugin: dump
    source:
      - on amd64: https://go.microsoft.com/fwlink/?LinkID=760868
      - on i386: https://go.microsoft.com/fwlink/?LinkID=760680
```
